eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      defaultZone: ${EUREKA_URI:http://20.62.231.42:8761/eureka}
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-ms
          uri: http://40.76.131.227:8002
          #uri: http://localhost:8002
          predicates:
            - Path=/api/v1/customers/**
        - id: product-ms
          uri: http://20.85.249.222:8003
          #uri: http://localhost:8003
          predicates:
            - Path=/api/v1/products/**
        - id: transaction-ms
          uri: http://20.84.13.193:8004
          #uri: http://localhost:8004
          predicates:
            - Path=/api/v1/transactions/**
        - id: card-ms
          uri: http://40.88.234.98:8005
          #uri: http://localhost:8005
          #uri: lb://CARD-MS
          predicates:
            - Path=/api/v1/cards/**
        - id: yanki-ms
          #uri: http://40.88.234.98:8005
          #uri: http://localhost:8005
          uri: lb://yanki-ms
          predicates:
            - Path=/api/v1/yankis/**