server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
spring:
  data:
    mongodb:
      uri: mongodb+srv://root:s3cr3t@cluster0.majt8.mongodb.net/db-customer?retryWrites=true&w=majority

