server:
  #port: ${PORT:${SERVER_PORT:0}}
  port: 8006
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: ${EUREKA_URI:http://192.168.100.119:8761/eureka}
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      #defaultZone: ${EUREKA_URI:http://20.62.231.42:8761/eureka}
  instance:
    hostname: localhost
    
resilience4j.circuitbreaker:
    instances:
        postCoinPurseCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10 
spring:
  data:
    mongodb:
      uri: mongodb+srv://root:s3cr3t@cluster0.u1nfg.mongodb.net/coin-purse?retryWrites=true&w=majority
